{{- $certmanager := lookup "v1" "Deployment" "" "cert-manager" -}}
{{- $clusterissuer := lookup "v1" "ClusterIssuer" .Release.Namespace "letsencrypt-http01-prod" -}}
{{- $enabled := .Values.certmanager.clusterIssuerEnabled -}}
{{- if and $certmanager (not $clusterissuer) $enabled -}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certmanager.clusterIssuerName }}
spec:
  acme:
    email: {{ .Values.certmanager.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        {{- if .Values.certmanager.ingressClassName -}}
        ingress:
          class: {{ .Values.certmanager.ingressClassName }}
        {{- end -}}
      selector: {}
{{- end -}}
