{{- if .Values.appEnv -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appEnvConfigMapName" . }}
{{- with .Values.appEnv }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
