{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.image.secret.name -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Values.image.secret.name }}"
data:
  {{- $username := .Values.image.secret.username | toString }}
  {{- $password := .Values.image.secret.password | toString }}
  {{- $auth := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry $username $password (printf "%s:%s" $username $password | b64enc) | b64enc }}
  .dockerconfigjson: {{ $auth }}
{{- end -}}
